"""Add location to Document model

Revision ID: 0669b23d931d
Revises: 
Create Date: 2025-12-04 11:47:52.551517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0669b23d931d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('location', sa.String(length=100), nullable=True))
    op.execute("UPDATE documents SET location = 'India'")
    op.alter_column('documents', 'location', nullable=False)
    op.create_index(op.f('ix_documents_location'), 'documents', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_location'), table_name='documents')
    op.drop_column('documents', 'location')
    # ### end Alembic commands ###
